#ifndef POSTERIORCMPWPVISDISEASE_H
#define POSTERIORCMPWPVISDISEASE_H

void gcmpwpvisdisease (int *pop, int *dis,
            int *K,
            int *n,
            int *samplesize, int *warmup, int *interval,
            double *mu0, double *mu1, double *dfmu,
            double *sigma0, double *sigma1,
	    double *dfsigma,
            double *lnlam0, double *lnlam1,
            double *nu0, double *nu1,
            double *beta0muprior, double *beta0sigmaprior,
            double *betatmuprior, double *betatsigmaprior,
            double *betaumuprior, double *betausigmaprior,
            double *lmemmu,
            double *memnu,
            double *memdfmu, double *memdfnu,
            double *memod,
            int *Np0i, int *Np1i,
            int *srd,
            int *numrec,
            double *rectime,
            int *maxcoupons,
            double *lnlamproposal,
            double *nuproposal,
            double *beta0proposal, double *betatproposal, double *betauproposal,
            double *tauproposal,
            double *lmemmuproposal, double *memnuproposal,
            int *N, int *maxN,
            double *sample,
            int *vsample,
            double *pos0u, double *pos1u,
            double *pos0d, double *pos1d,
            double *lpriorm,
            int *warmuptheta,
            int *warmupbeta,
            int *verbose
                         );

void MHwpmemdisease ( //int *dis,
            int *u, int *n, int *K, int *N, int *idiscount,
            double *beta0, double *beta0sd, double *betat, double *betatsd, 
            double *betau, double *betausd, 
            double *lmemmu,
            double *memdfmu,
            double *memnu,
            double *memdfnu,
            int *srd, 
            int *numrec, 
            double *rectime,
            int *maxcoupons,
            double *beta0proposal, double *betatproposal, double *betauproposal, 
            double *tauproposal,
            double *lmemmuproposal, double *memnuproposal, 
            double *beta0sample, double *betatsample, double *betausample,
            double *lmemmusample,
            double *memnusample,
            double *tau0sample, double *tau1sample,
            int *samplesize, int *staken, int *warmup, int *interval,
            int *verbose
         );

void MHcmpthetawpdisease (int *dis, int *u, int *Nk0, int *Nk1, int *K, int *idiscount,
            double *mu0, double *mu1, double *dfmu, 
            double *sigma0, double *sigma1, double *dfsigma,
            double *lnlamproposal, 
            double *nuproposal, 
            double *tauproposal, 
            int *N, int *Np0i, int *Np1i,
	    double *psample0, double *psample1,
            double *lnlamsample0, double *nusample0,
            double *lnlamsample1, double *nusample1,
            double *tau0sample, double *tau1sample,
            int *samplesize, int *staken, int *warmuptheta, int *interval,
            int *verbose
         );
#endif /* POSTERIORCMPWPVISDISEASE_H */
